apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zyrv9sm44-nodejs
  janus-idp.io/tekton: zyrv9sm44-nodejs
  backstage.io/kubernetes-id: zyrv9sm44-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zyrv9sm44-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
