apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zyrv9sm44-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zyrv9sm44-nodejs 
  name: zyrv9sm44-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zyrv9sm44-nodejs 
